project:
  type: website
  output-dir: docs
website:
  title: "Cognitive Psychology Experiments Using jsPsych"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/
      - premiere_experiment.qmd
format:
  html:
    theme: journal
    css: styles.css

editor: visual

