project:
  type: website
  output-dir: docs
website:
  title: "Cognitive Psychology Experiments Using jsPsych"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: slate
    css: styles.css

editor: visual

