project:
  type: website
  output-dir: docs
  resources:
    - "img/"
    - "jspsych/"
    - "farm/"
website:
  title: "Undergrad Cognitive Psychology Experiments Using jsPsych"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/
  
format:
  html:
    theme: journal
    css: styles.css

editor: visual

