---
title:  "A Weekly Cognitive Psychology Blog: Week Number Twelve"
author: "C Miller"
date: "2023-12-7"
---

## A Minerva Model in R

```{r, echo=FALSE}
library(devtools)
devtools::install_github("CrumpLab/RsemanticLibrarian")
library(lsa)
```

## Section I

```{r}

vector_length <- 10  #make random feature vectors for each item
num_items <- 100 # rows are items , columns are features

```

```{r}

#apply a function over a list or vector 
# use replicate for random number generation?

#sample with or without replacement
items <- t(replicate(num_items,
                     sample( rep(c(1,-1), vector_length / 2)
                     )
))

```

## Memory Matrix

```{r}
#define indices for old and new items
old <- 1:50  # encoding phase "old"
new <-51:100 # the model did not see this sequence from 51-100 of "new items"


#put old items into a memory matrix

#the memory of the model is a matrix
memory <- items[old,] # the first 50 items

```

## get an item to probe memory

```{r}
# each row of the matrix codes a memory trace

#matrix items has 100 items in it

probe_id <- 53 #all items in certain number,, then calculate the similarity to "memory"

probe <- items[probe_id,]

```

### similarity driven retrieval / test phase?

```{r}

#compute similarities

similarities <-
  RsemanticLibrarian::cosine_x_to_m(probe, memory)^5 #computes similarity between one vector and mutiple vectors in a matrix

#activate traces by weighted similarity

activations <- memory * c(similarities)

#calculate the echo response and global activation


```
